---
title: "Using the dawumr Package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using the dawumr Package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

**dawumr** provides convenience functions to pull and transform the election poll data from [dawum.de](https://dawum.de/) using R.

DAWUM ("Darstellung und Auswertung von Wahlumfragen") collects election poll results at the national level ("Bundestag") and federal state level ("Landtag"/"Abgeordnetenhaus") in Germany as well as polls for the European Parliament conducted by various institutes. The database goes back to 2017.

## Installation

The package can be installed from GitHub as a source package.

```r
# install.packages("devtools")
devtools::install_github("https://github.com/bydata/dawumr/")
```

## Basic Functionality

### Pulling Poll Results

Pull all survey results as a data frame:

```r
# Pull all available data, return only the data frame with the poll results
dawum_df <- load_dawum_results()
```

Pull only the latest results by election and institute:

```r
# Pull only the most recent polls for each election and institute
dawum_df_latest <- load_dawum_results(newest_only = TRUE)
```

Pull data as a list object with the database with separate tables for institutes, parliaments, etc.:

```r
# Pull all available data
dawum_db <- load_dawum_db()

# Pull only the most recent polls for each parliament and institute
dawum_db_latest <- load_dawum_db(newest_only = TRUE)
```

## Institutes and Parliaments

The DAWUM database covers polls for the national election in Germany, elections in the 16 German federal states, and the European Parliament conducted by a variety of institutes.

This package pulls all available data but makes no judgment about the quality of the polls or the institutes.


## Contributions

Many thanks to [\@timonscheuer](https://github.com/timonscheuer) for the inspiration and support with early bugfixing.

## License

Source: Data from dawum.de. License: <https://dawum.de/API/#Lizenz>, ODC Open Database License (ODC-ODbL).
